Using the standard Makefiles (in most cases) rather than the Makefile.win32 makefiles. Corrections to work with a user name containing a space.

diff --git a/tools/wings_package_win32 b/tools/wings_package_win32
--- a/tools/wings_package_win32
+++ b/tools/wings_package_win32
@@ -2,126 +2,140 @@
 #
 # Script for creating a self-contained Wings package for Windows.
 #
-# $Id: wings_package_win32,v 1.19 2003/09/07 05:57:50 bjorng Exp $
+# $Id: wings_package_win32,v 1.20 2003/09/11 11:17:47 bjorng Exp $
 #
+OS=`uname -o`
+if [ X$OS != XCygwin ]; then
+    echo "This script is supposed to be run in the" \
+	 "cygwin environement on windows only." >&2
+    exit 1
+fi
+
 if [ -z "$SF_PATH" ]; then
-    SF_PATH=c:/cygwin/home/Bjorng~1
+    SF_PATH="c:/cygwin/home/Bjorn Gustavsson"
 fi
 
 # Configurable stuff.
-WINGS_PATH=$SF_PATH/wings_releases
+WINGS_PATH="$SF_PATH/wings_releases"
 INSTALL=/usr/bin/install
-DEST_ROOT=$WINGS_PATH/wings3d
-ESDL_PATH=$SF_PATH/esdl
+DEST_ROOT="$WINGS_PATH/wings3d"
 NSIS=`which makensis 2>/dev/null`
 if [ -z "$NSIS" ]; then
     NSIS=c:/progra~1/nsis/makensis
 fi
 # End of configureable stuff.
 
+if [ -z "$ESDL_PATH" ]; then
+    echo "The environment variable ESDL_PATH must be set to " \
+	 "the top of the ESDL installation." >&2
+    exit 1
+fi
+
+#
+# Make sure we have a working GNU make.
+#
+echo -n "Checking make... "
+CYGMAKE=`which make 2>/dev/null`
+if [ -z "$CYGMAKE" ]; then
+    echo "no."
+    echo "Unable to find make. It seems you need to install more cygwin" \
+	"packages..." >&2
+    exit 1
+fi
+echo "ok"
 
 ERLANG_PATH=`which erl`
 ERLANG_PATH=`dirname $ERLANG_PATH`
 ERLANG_PATH=`dirname $ERLANG_PATH`
 
-temp=`pwd`
-
 # Copy the Wings application.
 
-for file in $WINGS_PATH/wings-*; do
-    if [ -d $file ]; then
+for file in "$WINGS_PATH"/wings-*; do
+    if [ -d "$file" ]; then
         latest_wings=$file
     fi
 done
 
 WINGS_VSN=`echo "$latest_wings" | sed -e 's/.*wings-//'`
 
-(cd $latest_wings; nmake -nologo -f Makefile.win32)
-(cd $latest_wings/win32; nmake -nologo -f Makefile.win32)
+echo "$latest_wings"
 
-dest=$DEST_ROOT
+cd "$latest_wings"
+echo `pwd`
+make
+case $? in
+    0) ;;
+    *)
+        echo "Failed to make Wings";
+        exit 1 ;;
+esac
 
-$INSTALL -d $dest $dest/ebin $dest/patches
+cd "$latest_wings/win32"
+nmake -nologo -f Makefile.win32
 
-cd $latest_wings
+cd "$latest_wings/plugins_src/win32_file"
+nmake -nologo
 
-$INSTALL -c -m 644 README AUTHORS license.terms vsn.mk $dest
-$INSTALL -c -m 644 ebin/* $dest/ebin
-$INSTALL -c -m 644 win32/wings.nsi $dest
-$INSTALL -c -m 644 win32/Wings3D.exe $dest
-$INSTALL -c -m 644 win32/wings.ico $dest
-$INSTALL -c -m 644 win32/install.ico $dest
+cd "$latest_wings"
+dest="$DEST_ROOT"
 
-$INSTALL -d $dest/plugins/fonts \
- $dest/plugins/import_export $dest/plugins/commands \
- $dest/plugins/primitives $dest/plugins/win32_file $dest/plugins/autouv
-$INSTALL -c -m 644 plugins/wp9_dialogs.beam $dest/plugins
-$INSTALL -c -m 644 plugins/fonts/* $dest/plugins/fonts
-$INSTALL -c -m 644 plugins/import_export/* $dest/plugins/import_export
-$INSTALL -c -m 644 plugins/commands/* $dest/plugins/commands
-$INSTALL -c -m 644 plugins/primitives/* $dest/plugins/primitives
-$INSTALL -c -m 644 plugins/win32_file/* $dest/plugins/win32_file
-$INSTALL -c -m 644 plugins/autouv/* $dest/plugins/autouv
+$INSTALL -d "$dest" "$dest/ebin" "$dest/patches"
+
+$INSTALL -c -m 644 README AUTHORS license.terms vsn.mk "$dest"
+$INSTALL -c -m 644 ebin/* "$dest/ebin"
+$INSTALL -c -m 644 win32/wings.nsi "$dest"
+$INSTALL -c -m 644 win32/Wings3D.exe "$dest"
+$INSTALL -c -m 644 win32/wings.ico "$dest"
+$INSTALL -c -m 644 win32/install.ico "$dest"
+
+$INSTALL -d "$dest/plugins/default" "$dest/plugins/fonts" \
+ "$dest/plugins/import_export" "$dest/plugins/commands" \
+ "$dest/plugins/primitives" "$dest/plugins/win32_file" \
+ "$dest/plugins/autouv"
+$INSTALL -c -m 644 plugins/default/wp9_dialogs.beam "$dest/plugins/default"
+$INSTALL -c -m 644 plugins/fonts/* "$dest/plugins/fonts"
+$INSTALL -c -m 644 plugins/import_export/* "$dest/plugins/import_export"
+$INSTALL -c -m 644 plugins/commands/* "$dest/plugins/commands"
+$INSTALL -c -m 644 plugins/primitives/* "$dest/plugins/primitives"
+$INSTALL -c -m 644 plugins/win32_file/* "$dest/plugins/win32_file"
+$INSTALL -c -m 644 plugins/autouv/* "$dest/plugins/autouv"
 
 # Copy the relevant parts of ESDL into the application.
 
-$INSTALL -d $dest/ebin $dest/priv
-$INSTALL -c -m 644  $ESDL_PATH/ebin/* $dest/ebin
-$INSTALL -c -m 644  $ESDL_PATH/priv/sdl_driver.dll $dest/priv
-$INSTALL -c -m 644  $ESDL_PATH/priv/SDL.dll $dest/priv
+$INSTALL -d "$dest/ebin" "$dest/priv"
+$INSTALL -c -m 644  "$ESDL_PATH"/ebin/* "$dest/ebin"
+$INSTALL -c -m 644  "$ESDL_PATH"/priv/sdl_driver.dll "$dest/priv"
+$INSTALL -c -m 644  "$ESDL_PATH"/priv/SDL.dll "$dest/priv"
 
-# Copy the relevant parts of Erlang into the application.
+# Copy the relevant parts of Erlang/OTP into the application.
 
-src=$ERLANG_PATH
-dest=$DEST_ROOT/erlang
-erts_src=$src/erts-*
-stdlib=`basename $src/lib/stdlib-*`
-kernel=`basename $src/lib/kernel-*`
+src="$ERLANG_PATH"
+dest="$DEST_ROOT/erlang"
+erts_src=`echo "$src"/erts-*`
+stdlib=`basename "$src"/lib/stdlib-*`
+kernel=`basename "$src"/lib/kernel-*`
 
-$INSTALL -d $dest/bin $dest/lib/$stdlib/ebin $dest/lib/$kernel/ebin
-$INSTALL -c -m 644 $src/lib/kernel-*/ebin/* $dest/lib/$kernel/ebin
-$INSTALL -c -m 644 $src/lib/stdlib-*/ebin/* $dest/lib/$stdlib/ebin
+$INSTALL -d "$dest/bin" "$dest/lib/$stdlib/ebin" "$dest/lib/$kernel/ebin"
+$INSTALL -c -m 644 "$src"/lib/kernel-*/ebin/* "$dest/lib/$kernel/ebin"
+$INSTALL -c -m 644 "$src"/lib/stdlib-*/ebin/* "$dest/lib/$stdlib/ebin"
 
-$INSTALL -c $erts_src/bin/werl.exe $dest/bin
-$INSTALL -c $erts_src/bin/erlexec.dll $dest/bin
-$INSTALL -c $erts_src/bin/beam.dll $dest/bin
-$INSTALL -c -m 644 $src/bin/start.boot $dest/bin
-$INSTALL -c $erts_src/bin/inet_gethost.exe $dest/bin/inet_gethost.exe
+$INSTALL -c "$erts_src/bin/werl.exe" "$dest/bin"
+$INSTALL -c "$erts_src/bin/erlexec.dll" "$dest/bin"
+$INSTALL -c "$erts_src/bin/beam.dll" "$dest/bin"
+$INSTALL -c -m 644 "$src/bin/start.boot" "$dest/bin"
+$INSTALL -c "$erts_src/bin/inet_gethost.exe" "$dest/bin/inet_gethost.exe"
 
 #
 # Remove files from OTP not needed.
 #
-tools/wings_reduce_otp $dest
+tools/wings_reduce_otp "$dest"
 
 # Strip debug information from all beam files.
-cd "$temp"
-
-cat >strip.erl <<'EOF'
--module(strip).
--export([strip/1]).
-
-strip([Wc]) ->
-    io:format("Stripping: ~p\n", [Wc]),
-    case catch strip_1(filelib:wildcard(Wc)) of
-        {'EXIT',Reason} ->
-            io:format("~P\n", [Reason,40]),
-            halt(1);
-        _ ->
-            halt(0)
-    end.
-    
-strip_1([B|Bs]) ->
-    {ok,{_,B}} = beam_lib:strip(B),
-    strip_1(Bs);
-strip_1([]) -> ok.
-EOF
-
-erlc strip.erl
-erl -noshell -pa . -run strip strip "$DEST_ROOT/erlang/lib/*/ebin/*.beam"
-erl -noshell -pa . -run strip strip "$DEST_ROOT/ebin/*.beam"
-erl -noshell -pa . -run strip strip "$DEST_ROOT/plugins/*/*.beam"
-erl -noshell -pa . -run strip strip "$DEST_ROOT/plugins/*.beam"
+cd "$latest_wings"
+erlc -o`cygpath -m /tmp` tools/strip.erl
+cd "$DEST_ROOT"
+erl -noshell -pa `cygpath -m /tmp` -run strip strip
 
 # Run NSIS
-cd $DEST_ROOT
+cd "$DEST_ROOT"
 "$NSIS" /DWINGS_VERSION=$WINGS_VSN wings.nsi
